### PR TITLE
perf: add multiplier to adjust trials value

### PR DESCRIPTION
**Pull request by minsii**
Test framework can adjust the value of trials through environment
variable SOS_TRIALS_MULTIPLIER (default 1, float).

### CODE REVIEW

**Comment by minsii** [comment]
@davidozog Can you please review this PR?

**Comment by jdinan** [comment]
Make sure these changes are also merged upstream in the main SOS repository or they will get lost with the next release update.

**Review by davidozog — COMMENTED** [review]
This looks good to me!  My only question/concern is whether you really want a float multiplier as opposed to simply setting the number of trials directly using some integer type.  But I could see the appeal of a float multiplier - and maybe your testing is already setup for the float multiplier?  If so, I'm happy to approve this.

And yes, we'll need to merge this upstream in SOS as well (I can post that PR after merging this, unless you prefer to @minsii).  I'll also include this in the `v1.4.x` branch.

**Comment by minsii** [comment]
@davidozog Thanks for reviewing. Using the multiplier allows us to keep different trails for small/large messages, and we don't need set different trails for different tests. The main reason to use `SOS_TRIALS_MULTIPLIER` in our test framework is that we run multiple jobs on a single machine. So we just want to reduce trails for all tests to shorten the run time.

**Review by davidozog — APPROVED** [review]

**Comment by davidozog** [comment]
@minsii - yeah, I suppose it makes sense to have just 1 knob to dial all tests longer or shorter based on the default values.

I suppose I'll take over merging this change into tests-sos and incorporating into SOS master and v1.4.x, unless you prefer to @minsii?

**Comment by wrrobin** [comment]
@minsii Would it be helpful if we add the multiplier in our argument list rather than reading it from the env var?

**Pull request merged**
